steps:
  # Build the editor service image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'services/editor-svc/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/script-improver-system-469119/pp-final/editor-svc:v12'
      - 'services/editor-svc'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/script-improver-system-469119/pp-final/editor-svc:v12'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
